version: "3.9"
services:
  mailbox:
    build:
      context: ./mailbox
    ports:
      - "4000:4000" # WebSocket
  relay:
    build:
      context: ./relay
    ports:
      - "4001:4001" # TCP
      - "4002:4002" # WebSocket
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - "8080:8080" # DevServer
      - "35729:35729" # LiveReload
    depends_on:
      - mailbox
      - relay
  # Selenium services
  chrome:
    volumes:
      - test-downloads:/tmp/test-downloads
    ports:
      - "5900:5900"
    image: selenium/node-chrome:4.1.3-20220405
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    profiles:
      - e2e
  edge:
    ports:
      - "5901:5900"
    image: selenium/node-edge:4.1.3-20220405
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    profiles:
      - e2e
  firefox:
    ports:
      - "5902:5900"
    image: selenium/node-firefox:4.1.3-20220405
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    profiles:
      - e2e
  selenium-hub:
    image: selenium/hub:4.1.3-20220405
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test:
        ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - e2e
  client-e2e:
    build: ./client-e2e
    env_file:
      - ./client-e2e/.env
    volumes:
      - ./client-e2e:/usr/src/app
      - test-downloads:/tmp/test-downloads
    depends_on:
      client:
        condition: service_started
      chrome:
        condition: service_started
      firefox:
        condition: service_started
      edge:
        condition: service_started
      selenium-hub:
        condition: service_healthy
    profiles:
      - e2e
volumes:
  test-downloads:
