name: transfer-repo-CI
on: [push, pull_request]
jobs:
  build:
    name: Build/Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [1.16.2]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: setup npm, yarn etc.
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install docker and docker-compose
        run: sudo apt-get install docker-compose

      - name: setup for running tests
        run: |
          cat <<EOF >> ./client-e2e/.env
          HOST_IP=localhost
          EOF

      - name: Setup docker images
        run: docker-compose build

      - name: build client
        run: docker-compose --profile e2e run client npm i

      - name: build client-e2e
        run: docker-compose --profile e2e run client-e2e npm i

      - name: run unit and integration tests
        run: |
          docker-compose --profile e2e up -d client
          docker-compose --profile e2e run client npm run test

      - name: stop the containers
        run: docker-compose --profile e2e down
